@startuml

abstract class Product
abstract class Creator {
    +FactoryMethod()
}
class ConcreteProduct
class ConcreteCreator
ConcreteProduct ..|> Product
ConcreteCreator ..|> Creator
ConcreteCreator ..> ConcreteProduct

@enduml